In [5]:
import numpy as np

In [11]:
# declare a list
age = [23,24,25,26]

In [13]:
# create array using np.array from the list
np_array = np.array(age)
np_array

array([23, 24, 25, 26])

In [15]:
# check the type of array
print(type(np_array))

<class 'numpy.ndarray'>


In [21]:
# shapre of the array
np_array.shape

(4,)

In [23]:
# create array of boooks with price
import math

In [25]:
math.sqrt(4)

2.0

In [31]:
math.ceil(64.8)

65

In [37]:
math.floor(64.8)

64

In [41]:
# one dimensional arrays
elemetns = ['Red',13,14,16,64,6+4j]
np.array(elemetns)

array(['Red', '13', '14', '16', '64', '(6+4j)'], dtype='<U64')

In [55]:
np.array([1,2,3,4])


array([1, 2, 3, 4])

In [57]:
np.array([1,2])

array([1. , 2.5, 3. ])

In [61]:
ar1 = np.array([1,2,3,4])
ar1/2

array([0.5, 1. , 1.5, 2. ])

In [65]:
ls1 = [1,2,3,4]
ls1/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [71]:
# multi dimensional arrays
ma1 = np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3]])
ma1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [73]:
ma1.shape

(4, 3)

In [83]:
a1 = np.array([[10,20,30],[40,50,60],[70,80,90],[100,110,120]])
a1

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [129]:
# initialize the array with zeros
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [131]:
np.zeros((2,2),int)

array([[0, 0],
       [0, 0]])

In [133]:
# initialize the array with ones
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [157]:
# fill the array with the data (3 - here)
np.full((2,2),3)

array([[3, 3],
       [3, 3]])

In [137]:
# initialize array with range of elements
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [139]:
np.arange(5,8)

array([5, 6, 7])

In [173]:
a = np.arange(1,8,2)
a

array([1, 3, 5, 7])

In [179]:
# reverse
np.arange(100,80,-2)

array([100,  98,  96,  94,  92,  90,  88,  86,  84,  82])

In [185]:
np.arange(3,8)

array([3, 4, 5, 6, 7])

In [189]:
np.random.rand()

0.5427701620527028

In [195]:
np.arange(np.random.rand(), np.random.rand()+1, np.random.rand())

array([0.64054489, 1.0586193 ])

In [197]:
np.random.rand(4)

array([0.55518181, 0.05096433, 0.1192488 , 0.129147  ])

In [199]:
np.random.rand(4,2)

array([[0.66718076, 0.16278913],
       [0.13625752, 0.99105857],
       [0.06384675, 0.58871497],
       [0.67976337, 0.96205768]])

In [223]:
np.random.randint(5)

1

In [227]:
np.random.randint(2,5)

3

In [249]:
np.random.randint(2,8,4)

array([2, 7, 3, 3])

In [255]:
elemetns = ['Red',13,14,16,64,6+4j]
np.random.choice(elemetns)

'14'

In [488]:
import numpy as np
import os

class Play:
    def __init__(self):
        self.combinations = ['Rock', 'Paper', 'Scissor']

    def username(self):
        username = os.getlogin()
        return username.title()
    
    def user(self, user_value):
        if user_value not in self.combinations:
            print('Invalid choice. Try again.')
            return None
        return user_value

    def computer(self):
        computer_choice = np.random.choice(self.combinations)
        return computer_choice
    
    def rules(self, user1, user2):
        if user1 == user2:
            print("It's a tie!")
        elif (user1 == 'Rock' and user2 == 'Scissor') or \
             (user1 == 'Paper' and user2 == 'Rock') or \
             (user1 == 'Scissor' and user2 == 'Paper'):
            print('User is the winner!')
        else:
            print('Computer is the winner!')


if __name__ == '__main__':
    game = Play()
    username = game.username()
    user_value = input("Enter the value from 'Rock', 'Paper', 'Scissor'")
    user_choice = game.user(user_value)
    if user_choice is not None:
        computer_choice = game.computer()
        print(f'{username} has choosed {user_choice} and Computer chosen: {computer_choice} and ')
        game.rules(user_choice, computer_choice)

Enter the value from 'Rock', 'Paper', 'Scissor' Rock


Rajnish has choosed Rock and Computer chosen: Paper and 
Computer is the winner!


In [334]:
ar1.shape

(4,)

In [364]:
ar3 = np.array([23,65,112,39,2,55,-65,120,5,11])
ar3

array([ 23,  65, 112,  39,   2,  55, -65, 120,   5,  11])

In [376]:
np.sort(ar3)[::-1]

array([120, 112,  65,  55,  39,  23,  11,   5,   2, -65])

In [380]:
np.argsort(ar3)[::-1]

array([7, 2, 1, 5, 3, 0, 9, 8, 4, 6])

In [390]:
# union -  meging multiple arrays
ar4 = np.array([11,12,13])
ar5 = np.array([13,14,15])
ar6 = np.array([11,12,16])

In [392]:
ar4,ar5,ar6

(array([11, 12, 13]), array([13, 14, 15]), array([11, 12, 16]))

In [398]:
# vertical stack - VSTACK
np.vstack([ar4,ar5,ar6])

array([[11, 12, 13],
       [13, 14, 15],
       [11, 12, 16]])

In [400]:
np.hstack([ar4,ar5,ar6])

array([11, 12, 13, 13, 14, 15, 11, 12, 16])

In [402]:
np.column_stack([ar4,ar5,ar6])

array([[11, 13, 11],
       [12, 14, 12],
       [13, 15, 16]])

In [408]:
np.intersect1d(ar4,ar6)

array([11, 12])

In [418]:
np.setdiff1d(ar4,ar6)

array([13])

In [420]:
np.setdiff1d(ar6,ar4)

array([16])

In [424]:
np.sum([ar4,ar6])

75

In [434]:
np.sum([ar4,ar6], axis=0)

array([22, 24, 29])

In [442]:
ar8 = np.array([[10,20,30],
                [40,50,60]])
ar9 = np.array([[11,22,33],
                [44,55,66]])

In [444]:
np.sum([ar8,ar9],axis=0)

array([[ 21,  42,  63],
       [ 84, 105, 126]])

In [446]:
np.sum([ar8,ar9],axis=1)

array([[50, 70, 90],
       [55, 77, 99]])

In [452]:
ar10 = np.array([[10,20,30],[40,50,60]])
ar10

array([[10, 20, 30],
       [40, 50, 60]])

In [454]:
ar10.transpose()

array([[10, 40],
       [20, 50],
       [30, 60]])

In [456]:
np.transpose(ar10)

array([[10, 40],
       [20, 50],
       [30, 60]])

In [466]:
# identity metrix - 1's in diagonal and 0's in other positions of a matrix
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [484]:
np.eye(4,4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [486]:
# save numpy file
# np.save('mynmpy',ar8)

In [ ]:
# open the numpy file
# np.load(mynmpy.npy)